baseURL = 'https://sillon-fictionnel.club/'
title = 'le sillon fictionnel'
theme = 'writeonly'
copyright = '© 2024 Le Sillon Fictionnel - contenu sous licence creativecommons.org CC BY 4.0. Le Sillon Fictionnel est mis à disposition selon les termes de la Licence Creative Commons Attribution - Partage dans les Mêmes Conditions 4.0 International.'                                                              
languageCode = 'fr'
defaultContentLanguage = 'fr'
defaultContentLang = 'fr'

[mediaTypes]
  [mediaTypes."application/atom+xml"]
     suffixes = "xml"

[outputFormats]
  [outputFormats.Atom]
     mediaType = "application/atom+xml"
     baseName = "atom"
     isPlainText = false

[outputs]
    home = [ "HTML", "Atom", "RSS" ]

[params]
  title = 'sillon-fictionnel.club'
  description = 'Le Sillon Fictionnel - Un espace dédié à la passion de la lecture et la culture au sein d’un club un peu atypique. Critiques - livre, art et culture.'
  mastodon = 'https://paperbay.org/@sillon_fictionnel'
  github = 'https://github.com/adulau/sillon-fictionnel'
  [socialIcons]
    name = 'rss'
    url = 'https://sillon-fictionnel.club'
  [favicons]
    themeColor = '#FFFFFF'
    backgroundColor = '#FFFFFF'
    faviconColor = '#000000'

[menus]
  [[menus.main]]
    name = "à propos"
    url = "/apropos"
    weight = 1
  [[menus.main]]
    name = "Les critiques"
    url = "/post"
    weight = 2
  [[menus.main]]
    name = "mots-clés"
    url = "/tags"
    weight = 3
  [[menus.main]]
    name = "les librairies"
    url = "/les-librairies"
    weight = 4

[taxonomies]
  series = 'series'
  tags = 'tags'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

