+++
author = "H. Galois"
title = "La plus secrète mémoire des hommes"
date = "2025-07-05"
tags = [
    "livre","critique", "chronique", "roman"
]
ISBN = "9782848768878"
+++

_Un livre de Mohamed Mbougar Sarr_

C’est l’histoire d’un écrivain sénégalais entre les mains duquel tombe un vieux livre oublié, « Le labyrinthe de l’inhumain », d’un certain T. C. Elimane, auteur d’une seule œuvre dont plus personne ou presque ne sait plus rien. Commence alors la chronique d’une quête, à la recherche de l’ombre d’une étoile filante de la littérature. Le narrateur, dans cette « histoire impossible à raconter », croise un poète convaincu qu’un poète qui a plus de 120 lecteurs est suspect et d’autres auteurs atteints « d’incontinence littéraire »… Ils parlent de littérature jusqu’au bout de la nuit, constatent que le monde n’est pas si perdu puisque cela advient, et nous y entraînent, emmaillotés dans un style envoûtant.
« Les grandes œuvres appauvrissent et doivent toujours appauvrir. Elles ôtent de nous le superflu » (p. 53). Mais parfois il ne reste presque plus rien. Alors c’est un long périple pour maintenir en vie une mémoire. C’est une quête impossible, pourtant intimement intriquée avec la vie, dont il ne surgira qu’une vaste, intense, mais imprécise idée : la littérature comme mystique.
Le livre dit aussi l’émigration, avec par exemple de superbes pages sur l’appel aux parents, que l’auteur voit comme étant caractéristique des émigrés, mais qui est peut-être un universel.
Je me suis demandé si la quête du narrateur n’était pas, paradoxalement et malgré son érudition – longtemps que je n’avais pas lu le mot shiboleth – et sa géniale composition, un processus de libération de la littérature. On y croise Borges, Sábato, Gombrowicz et d’autres pointures, on les y croise et on les y lit, textes cités ou seulement évoqués ; l’auteur joue des emprunts, comme semble avoir fait le mystérieux T. C. Elimane (citons par exemple la référence à l’idée que le hasard, qui n’est qu’un destin qu’on ignore, idée citée plusieurs fois – par exemple p. 336 – et qui est clairement un emprunt à Borges qui en faisait une équivalence).
Le livre, à travers ses multiples voix imbriquées, de récits dans les récits, se demande si le mal n’est pas la seule grande question. Confirmation, si besoin en était, que la littérature se réinvente en se répétant. Et cette grande question en amène donc peut-être une autre : et si le livre essentiel, finalement, ne pouvait s’écrire ?

![](/images/Laplussecretememoire.jpeg)

« À ce moment le vide se trancha la gorge, et dans le cri muet qu’ouvrit sa lame dans sa chair, tu crus entendre s’écimer, chue de la tête pantelante, une dernière hypothèse, terrible et terriblement calme : le livre essentiel ne s’écrit pas » (p. 142). L’hypothèse m’a fait penser à mon père, grand écrivain qui n’a jamais rien écrit, mais dont la façon de raconter les histoires relevait assurément de la littérature. Nul hasard, il l’aimait. D’ailleurs, la difficulté à raconter la vie d’Elimane m’évoque la mienne à parler ou écrire sérieusement sur mon père. Mais peu importe, revenons à l’hypothèse. Je pense parfois que je peux avoir reçu en héritage cette faculté de raconter sans écrire, mais que, l’ignorant, je m’escrime à écrire. Peut-être que je sais ce qu’énonce Chérif, à qui le narrateur rend visite : « Je te dis qu’il vaut mieux ne pas écrire si tu n’as pas au moins l’ambition de faire trembler l’âme d’une personne » (p. 445).
Le mal il vient souvent des patries, de la guerre et de l’exil, qui exigent des engagements contre les siens, d’autant plus douloureux quand ils affectent les colonisés. La langue est bien sûr l’autre grande affaire de « La plus secrète mémoire des hommes ». D’abord par ce que Sarr mène une longue démonstration de la puissance du style ; le livre s’avale, d’un féroce appétit, et je suis convaincu que cela tient davantage aux manières du récit qu’à ses péripéties. De Sarr, une jambe en Afrique l’autre en Europe, surgissent des images merveilleuses qu’on n’invente guère chez les vieilles souches de l’hexagone (par exemple : « […] Ellenstein décide de suivre ce qu’il n’est pas convenable de nommer une piste, mais un froissement de fourrés dans une jungle drue » (p. 301).
Mais c’est aussi une exploration belle et subtile de ce que signifie s’exprimer et écrire dans une langue qui n’est pas celle de ses aïeux, qui est celle du colonisateur. Lorsque la littérature devient son « pays réel » (p. 294), peu importe sa langue. Sarr, peu importe ou pas, écrit d’un style magistral, inventif, lumineux, musical.
C’est enfin un roman poétique ; les pages et les chapitres sont structurés de poésie, une poésie qui toujours actionne l’histoire – mais n’est-ce pas l’étymologie de poésie, « faire », « créer » ? –… Prenons la page 389, par exemple : « Mais soit, me disais-je, soit ; j’écrirai donc comme on trahit son pays, c’est-à-dire comme on se choisit pour terre non le pays natal, mais le pays fatal, la patrie à laquelle notre vie profonde nous destine depuis toujours, la patrie de l’intérieur, celle des souvenirs chaleureux et celle des ténèbres glacées, la patrie des rêves premiers la patrie des peurs et des hontes ruisselant en troupeau sur les flancs de l’âme, la patrie de toute la chiennerie errante le long des nuits couleur pétrole, de rues blanches, de villes que même les fantômes auraient désertées, la patrie des visions cristallisées d’amour et d’innocence, mais la patrie aussi de la folie rieuse et des entassements de crânes et de la lucidité impitoyable qui dévore le foie, la patrie de toute la solitude possible et de tout le silence disponible, la seule patrie que je trouvais habitable (et par habitable je veux dire : impossible à perdre ou à haïr, impossible à exposer à une nostalgie sentimentale et superficielle, impossible à prendre comme prétexte ou otage en vue d’accrocher la gratifiante breloque de l’exil à la poitrine et, enfin, la patrie impossible à défendre, puisqu’elle se défend toute seule de ses imprenables contreforts et n’exige de sacrifice que celui de notre paresse et de nos envies de faire l’amour tout le temps). Quelle est donc cette patrie ? Tu la connais : c’est évidemment la patrie des livres : les livres lus et aimés, les livres lus et honnis, les livres qu’on rêve d’écrire, les livres insignifiants qu’on a oubliés et dont on ne sait même plus si on les a ouverts un jour, les livres qu’on prétend avoir lus, les livres qu’on ne lira jamais, mais dont on ne se séparerait pour rien au monde, les livres qui attendent leur heure dans une nuit patiente, avant le crépuscule éblouissant des lectures de l’aube. Oui, disais-je, oui, je serai citoyenne de cette patrie-là, je ferai allégeance à ce royaume, le royaume de ma bibliothèque ».
C’est un grand et beau livre, une cathédrale à la littérature que je n’ai pas pu lâcher. Si un jour je perds la vue, j’aimerais qu’on me dise : « Un homme sans imagination, aveugle ou pas, est toujours malheureux. Mais toi tu n’es pas comme ça. Tu as vu, mais tu sais encore imaginer des choses à voir » (p. 211).

***

La plus secrète mémoire des hommes  
Mohamed Mbougar Sarr  
Le livre de poche, 566 p.
2021
