name = "Write-Only Hugo Theme"
license = "MIT"
licenselink = "https://gitlab.com/writeonlyhugo/writeonlyhugo-theme/-/blob/master/LICENSE"
description = "A simple, clean and straightforward blog theme."

homepage = "https://gitlab.com/writeonlyhugo/writeonlyhugo-theme/"
demosite = "https://writeonlyhugo.gitlab.io/writeonlyhugo-demo/"

tags = ["blog", "responsive", "personal", "light", "bootstrap" ]
features = []

[author]
  name = "Iago Bozza"
  homepage = "https://writeonlycode.io/"
